"""Persistent storage for saved WiFi networks, backed by .nmconnection files."""

import configparser
import os
import subprocess
import tempfile
import threading
import uuid
from enum import IntEnum

from openpilot.common.swaglog import cloudlog
from openpilot.common.utils import sudo_read


NM_CONNECTIONS_DIR = "/data/etc/NetworkManager/system-connections"
RUNTIME_CONNECTIONS_DIR = "/run/NetworkManager/system-connections"
NETPLAN_CONNECTIONS_DIR = "/data/etc/netplan"

# Only key-mgmt values we can actually drive via wpa_supplicant. Anything else
# (wpa-eap, sae, ieee8021x, ...) gets skipped on load. Coercing those to
# psk="" would render as key_mgmt=NONE in wpa_supplicant.conf, silently turning
# a secure profile into an open one for the same SSID and inviting open spoofing.
_SUPPORTED_KEY_MGMT = {"wpa-psk", "none"}
_SUPPORTED_WIFI_OPTIONS = {"ssid", "mode", "hidden", "bssid"}
_SUPPORTED_SECURITY_OPTIONS = {"key-mgmt", "psk", "psk-flags", "auth-alg"}
_SUPPORTED_IPV4_METHODS = {"auto"}
_SUPPORTED_IPV6_METHODS = {"auto", "ignore"}
_SUPPORTED_IPV4_OPTIONS = {"method", "dns-priority"}
_SUPPORTED_IPV6_OPTIONS = {"method", "addr-gen-mode"}
# NetworkManager-backed openpilot profiles use this DNS priority. The direct
# stack does not consume it, but retaining it keeps the keyfile rollback-safe.
_OPENPILOT_DNS_PRIORITY = "600"
_KEYFILE_ESCAPES = {
  "\\": "\\",
  "n": "\n",
  "r": "\r",
  "s": " ",
  "t": "\t",
}


class MeteredType(IntEnum):
  UNKNOWN = 0
  YES = 1
  NO = 2


def _canonical_filename(file_uuid: str, ssid: str) -> str:
  """`<uuid>-<ssid>.nmconnection` matches netplan's runtime keyfile naming. UUID is the
  stable handle; the SSID suffix is purely cosmetic, so it gets sanitized lossily."""
  ssid_safe = ssid.encode("utf-8", errors="surrogateescape").decode("utf-8", errors="replace")
  ssid_safe = ssid_safe.replace("/", "_").replace("\0", "_")
  return f"{file_uuid}-{ssid_safe}.nmconnection"


def _decode_keyfile_string(value: str) -> str:
  """Decode GLib keyfile string escapes."""
  decoded = []
  i = 0
  while i < len(value):
    if value[i] == "\\" and i + 1 < len(value):
      escaped = _KEYFILE_ESCAPES.get(value[i + 1])
      if escaped is not None:
        decoded.append(escaped)
        i += 2
        continue
    decoded.append(value[i])
    i += 1
  return "".join(decoded)


def _encode_keyfile_string(value: str) -> str:
  """Encode GLib keyfile string escapes, including boundary spaces."""
  leading_spaces = len(value) - len(value.lstrip(" "))
  trailing_spaces = len(value) - len(value.rstrip(" "))
  encoded = []
  for i, char in enumerate(value):
    if char == "\\":
      encoded.append("\\\\")
    elif char == "\n":
      encoded.append("\\n")
    elif char == "\r":
      encoded.append("\\r")
    elif char == "\t":
      encoded.append("\\t")
    elif char == " " and (i < leading_spaces or i >= len(value) - trailing_spaces):
      encoded.append("\\s")
    else:
      encoded.append(char)
  return "".join(encoded)


def _encode_keyfile_ssid(ssid: str) -> str:
  if not ssid:
    return ""
  return ";".join(str(b) for b in ssid.encode("utf-8", errors="surrogateescape")) + ";"


def _decode_keyfile_ssid(ssid: str) -> str:
  """Decode NM keyfile byte-list SSIDs and escaped literal semicolons."""
  ssid = _decode_keyfile_string(ssid)
  if r"\;" in ssid:
    return ssid.replace(r"\;", ";")
  if not ssid.endswith(";"):
    return ssid

  try:
    ssid_bytes = bytes(int(p) for p in ssid[:-1].split(";"))
  except ValueError:
    return ssid

  if not ssid_bytes:
    return ssid
  if all(b == 0 for b in ssid_bytes):
    return ""
  return ssid_bytes.decode("utf-8", errors="surrogateescape")


class NetworkStore:
  """Persistent storage for saved WiFi networks using .nmconnection files."""

  def __init__(self, directory: str = NM_CONNECTIONS_DIR, runtime_directory: str | None = None, netplan_directory: str | None = None):
    self._directory = directory
    # Production upgrades can have keyfiles generated by netplan in /run but no
    # persistent copy yet. Custom test stores should remain isolated unless an
    # explicit runtime directory is supplied.
    self._runtime_directory = RUNTIME_CONNECTIONS_DIR if directory == NM_CONNECTIONS_DIR else None
    if runtime_directory is not None:
      self._runtime_directory = runtime_directory
    self._netplan_directory = NETPLAN_CONNECTIONS_DIR if directory == NM_CONNECTIONS_DIR else None
    if netplan_directory is not None:
      self._netplan_directory = netplan_directory
    self._lock = threading.Lock()
    self._networks: dict[str, dict] = {}
    self._profiles: dict[str, list[dict]] = {}
    self._load()

  def _load(self):
    self._networks = {}
    self._profiles = {}
    sources = [(self._directory, False)]
    if self._runtime_directory is not None:
      sources.append((self._runtime_directory, True))

    persistent_ssids: set[str] = set()
    for directory, imported in sources:
      try:
        filenames = sorted(os.listdir(directory))
      except OSError:
        continue
      for fname in filenames:
        self._load_keyfile(directory, fname, imported, persistent_ssids)

  def _load_keyfile(self, directory: str, fname: str, imported: bool, persistent_ssids: set[str]):
    if not fname.endswith(".nmconnection"):
      return
    fpath = os.path.join(directory, fname)
    try:
      cp = configparser.ConfigParser(interpolation=None)
      raw = sudo_read(fpath)
      if raw:
        cp.read_string(raw)
      else:
        cp.read(fpath)

      # NM keyfile schema documents [802-11-wireless]/[802-11-wireless-security]
      # as canonical with [wifi]/[wifi-security] as aliases. AGNOS NM 1.46 writes
      # the alias form for every wifi profile it generates; only hand-written or
      # imported keyfiles can use canonical names. We deliberately accept only
      # the alias spelling so a keyfile we can't round-trip (we only write
      # [wifi] back) remains untouched.
      if not cp.has_section("wifi"):
        return
      ssid = _decode_keyfile_ssid(cp.get("wifi", "ssid", fallback=""))
      mode = cp.get("wifi", "mode", fallback="infrastructure")
      if not ssid or mode != "infrastructure":
        return
      if set(cp.options("wifi")) - _SUPPORTED_WIFI_OPTIONS:
        cloudlog.warning(f"NetworkStore: skipping {ssid!r} with unsupported Wi-Fi options")
        return
      file_uuid = cp.get("connection", "uuid", fallback="")
      # Persistent /data profiles are authoritative over netplan's runtime
      # copies, including unsupported or disabled persistent profiles.
      if imported and ssid in persistent_ssids:
        primary = self._networks.get(ssid)
        if primary is not None and primary.get("_runtime_filename") is None:
          primary["_runtime_filename"] = fname
          primary["_netplan_filename"] = f"90-NM-{file_uuid}.yaml" if file_uuid else None
        return
      if not imported:
        persistent_ssids.add(ssid)

      # An open profile has no [wifi-security] section. A secure profile with a
      # key-mgmt we can't reproduce (wpa-eap, sae, ...) must be skipped entirely.
      psk = ""
      if cp.has_section("wifi-security"):
        key_mgmt = cp.get("wifi-security", "key-mgmt", fallback="").lower()
        if key_mgmt not in _SUPPORTED_KEY_MGMT:
          cloudlog.warning(f"NetworkStore: skipping {ssid!r} with unsupported key-mgmt={key_mgmt!r}")
          return
        # NM stores WEP as `key-mgmt=none` plus `wep-key*`/`wep-key-type`/`auth-alg=shared`.
        # Loading those as open (psk="") would let _generate_wpa_conf demote the secured
        # SSID to key_mgmt=NONE, enabling auto-association to an open spoof of the same SSID.
        wep_keys = ("wep-key0", "wep-key1", "wep-key2", "wep-key3", "wep-key-type", "auth-alg")
        if key_mgmt == "none" and any(cp.has_option("wifi-security", k) for k in wep_keys):
          cloudlog.warning(f"NetworkStore: skipping {ssid!r} (WEP profile, unsupported)")
          return
        unsupported_security_options = set(cp.options("wifi-security")) - _SUPPORTED_SECURITY_OPTIONS
        auth_alg = cp.get("wifi-security", "auth-alg", fallback="").lower()
        psk_flags = cp.getint("wifi-security", "psk-flags", fallback=0)
        if unsupported_security_options or auth_alg not in ("", "open") or psk_flags != 0:
          cloudlog.warning(f"NetworkStore: skipping {ssid!r} with unsupported security constraints")
          return
        psk = _decode_keyfile_string(cp.get("wifi-security", "psk", fallback=""))
        # NM agent-managed secrets (psk-flags=1) live outside the keyfile. We can't
        # drive them via wpa_supplicant, and loading with psk="" would render as
        # key_mgmt=NONE, silently demoting a secure profile to open and inviting spoofs.
        if key_mgmt == "wpa-psk" and not psk:
          cloudlog.warning(f"NetworkStore: skipping {ssid!r} (wpa-psk with no inline secret)")
          return

      # connection.autoconnect=false is user/provisioning intent. Do not load it
      # only to have ENABLE_NETWORK all silently re-arm the auto-join.
      if not cp.getboolean("connection", "autoconnect", fallback=True):
        cloudlog.warning(f"NetworkStore: skipping {ssid!r} (connection.autoconnect=false)")
        return

      ipv4 = dict(cp["ipv4"]) if cp.has_section("ipv4") else {"method": "auto"}
      ipv6 = dict(cp["ipv6"]) if cp.has_section("ipv6") else {"method": "auto"}
      ipv4_method = ipv4.get("method", "auto").lower()
      ipv6_method = ipv6.get("method", "auto").lower()
      unsupported_ipv4_options = set(ipv4) - _SUPPORTED_IPV4_OPTIONS
      unsupported_ipv6_options = set(ipv6) - _SUPPORTED_IPV6_OPTIONS
      ipv4_dns_priority = ipv4.get("dns-priority")
      ipv6_addr_gen_mode = ipv6.get("addr-gen-mode", "default").lower()
      if (ipv4_method not in _SUPPORTED_IPV4_METHODS
          or ipv6_method not in _SUPPORTED_IPV6_METHODS
          or unsupported_ipv4_options
          or unsupported_ipv6_options
          or ipv4_dns_priority not in (None, _OPENPILOT_DNS_PRIORITY)
          or ipv6_addr_gen_mode != "default"):
        cloudlog.warning(f"NetworkStore: skipping {ssid!r} with unsupported addressing configuration")
        return

      # getint/getboolean can raise ValueError on malformed values; skip the bad profile.
      entry = {
        "psk": psk,
        "metered": cp.getint("connection", "metered", fallback=0),
        "priority": cp.getint("connection", "autoconnect-priority", fallback=0),
        "hidden": cp.getboolean("wifi", "hidden", fallback=False),
        "bssid": cp.get("wifi", "bssid", fallback=""),
        "uuid": file_uuid,
        "_ipv4": ipv4,
        "_ipv6": ipv6,
        # Remember the on-disk filename so save/remove stay consistent with noncanonical files.
        "_filename": None if imported else fname,
        "_runtime_filename": fname if imported else None,
        "_netplan_filename": f"90-NM-{file_uuid}.yaml" if imported and file_uuid else None,
      }
      profiles = self._profiles.setdefault(ssid, [])
      if file_uuid and any(profile.get("uuid") == file_uuid for profile in profiles):
        return
      profiles.append(entry)
      self._networks.setdefault(ssid, entry)
    except (configparser.Error, ValueError):
      return

  def _render_nmconnection(self, ssid: str, entry: dict) -> tuple[str, dict]:
    file_uuid = entry.get("uuid")
    if not file_uuid:
      try:
        file_uuid = str(uuid.uuid5(uuid.NAMESPACE_DNS, ssid))
      except UnicodeEncodeError:
        ssid_hex = ssid.encode("utf-8", errors="surrogateescape").hex()
        file_uuid = str(uuid.uuid5(uuid.NAMESPACE_OID, ssid_hex))
    entry = dict(entry)
    entry["uuid"] = file_uuid

    canonical_fname = _canonical_filename(file_uuid, ssid)
    canonical_path = os.path.join(self._directory, canonical_fname)
    stored_fname = entry.get("_filename")
    entry["_filename"] = canonical_fname

    cp = configparser.ConfigParser(interpolation=None)
    connection_id = ssid.encode("utf-8", errors="surrogateescape").decode("utf-8", errors="replace")
    cp["connection"] = {
      "id": _encode_keyfile_string(connection_id),
      "uuid": file_uuid,
      "type": "wifi",
      "metered": str(entry.get("metered", 0)),
      "autoconnect-priority": str(entry.get("priority", 0)),
    }
    wifi = {
      "ssid": _encode_keyfile_ssid(ssid),
      "mode": "infrastructure",
      "hidden": str(entry.get("hidden", False)).lower(),
    }
    if entry.get("bssid"):
      wifi["bssid"] = entry["bssid"]
    cp["wifi"] = wifi

    psk = entry.get("psk", "")
    if psk:
      cp["wifi-security"] = {
        "key-mgmt": "wpa-psk",
        "psk": _encode_keyfile_string(psk),
      }

    cp["ipv4"] = entry.get("_ipv4", {"method": "auto"})
    cp["ipv6"] = entry.get("_ipv6", {"method": "auto"})

    with tempfile.NamedTemporaryFile(mode="w", dir="/tmp", delete=False) as f:
      cp.write(f)
      temp_path = f.name

    try:
      os.chmod(temp_path, 0o600)
      subprocess.run(["sudo", "install", "-d", "-m", "755", self._directory], check=True)
      subprocess.run(["sudo", "install", "-o", "root", "-g", "root", "-m", "600", temp_path, canonical_path], check=True)
    finally:
      try:
        os.unlink(temp_path)
      except FileNotFoundError:
        pass

    # Keep one canonical filename even when the tracked profile uses another name.
    if stored_fname and stored_fname != canonical_fname:
      stored_path = os.path.join(self._directory, stored_fname)
      result = subprocess.run(["sudo", "rm", "-f", stored_path], check=False)
      # If cleanup fails (FS read-only, etc.) both files survive. Make both files
      # hold the same content so they remain one UUID-equivalent profile. Pin
      # _filename to the stored name so each update retries the cleanup.
      if result.returncode != 0:
        cloudlog.warning(f"NetworkStore: cleanup of noncanonical {stored_fname} failed; mirroring content to keep both files in sync")
        try:
          subprocess.run(["sudo", "install", "-o", "root", "-g", "root", "-m", "600", os.path.join(self._directory, canonical_fname), stored_path], check=True)
        except Exception:
          cloudlog.exception("NetworkStore: failed to mirror keyfile to noncanonical path")
        entry["_filename"] = stored_fname

    runtime_filename = entry.get("_runtime_filename")
    if self._runtime_directory is not None and runtime_filename:
      runtime_path = os.path.join(self._runtime_directory, runtime_filename)
      result = subprocess.run(["sudo", "rm", "-f", runtime_path], check=False)
      if result.returncode != 0:
        cleanup_result = subprocess.run(["sudo", "rm", "-f", canonical_path], check=False)
        if cleanup_result.returncode != 0:
          raise OSError(f"failed to remove {runtime_path} and roll back {canonical_path}")
        raise OSError(f"failed to remove {runtime_path}")
      entry["_runtime_filename"] = None

    netplan_filename = entry.get("_netplan_filename")
    if self._netplan_directory is not None and netplan_filename:
      netplan_path = os.path.join(self._netplan_directory, netplan_filename)
      result = subprocess.run(["sudo", "rm", "-f", netplan_path], check=False)
      if result.returncode != 0:
        cleanup_result = subprocess.run(["sudo", "rm", "-f", canonical_path], check=False)
        if cleanup_result.returncode != 0:
          raise OSError(f"failed to remove {netplan_path} and roll back {canonical_path}")
        raise OSError(f"failed to remove {netplan_path}")
      entry["_netplan_filename"] = None

    return file_uuid, entry

  def get_all(self) -> dict[str, dict]:
    with self._lock:
      return {k: dict(v) for k, v in self._networks.items()}

  def get_profiles(self) -> list[tuple[str, dict]]:
    with self._lock:
      return [
        (ssid, dict(entry))
        for ssid, profiles in self._profiles.items()
        for entry in profiles
      ]

  def get(self, ssid: str) -> dict | None:
    with self._lock:
      entry = self._networks.get(ssid)
      return dict(entry) if entry else None

  def get_tethering_password(self, ssid: str) -> str | None:
    directories = [self._directory]
    if self._runtime_directory is not None:
      directories.append(self._runtime_directory)

    for directory in directories:
      try:
        filenames = os.listdir(directory)
      except OSError:
        continue
      for fname in filenames:
        if not fname.endswith(".nmconnection"):
          continue
        try:
          raw = sudo_read(os.path.join(directory, fname))
          if not raw:
            continue
          cp = configparser.ConfigParser(interpolation=None)
          cp.read_string(raw)
          profile_ssid = _decode_keyfile_ssid(cp.get("wifi", "ssid", fallback=""))
          if cp.get("wifi", "mode", fallback="infrastructure") != "ap" or profile_ssid != ssid:
            continue
          if cp.get("wifi-security", "key-mgmt", fallback="").lower() != "wpa-psk":
            continue
          password = _decode_keyfile_string(cp.get("wifi-security", "psk", fallback=""))
          if password:
            return password
        except (configparser.Error, OSError, ValueError):
          continue
    return None

  def save_network(self, ssid: str, psk: str | None = None, metered: int | None = None, hidden: bool | None = None):
    with self._lock:
      current = self._networks.get(ssid)
      existing = dict(current or {})
      if psk is not None:
        existing["psk"] = psk
      elif "psk" not in existing:
        existing["psk"] = ""
      if metered is not None:
        existing["metered"] = metered
      elif "metered" not in existing:
        existing["metered"] = 0
      if hidden is not None:
        existing["hidden"] = hidden
      elif "hidden" not in existing:
        existing["hidden"] = False

      if current is not None and psk is not None:
        updated_profiles = []
        updated_primary = None
        for profile in self._profiles.get(ssid, [current]):
          candidate = existing if profile is current else {**profile, "psk": psk}
          file_uuid, updated = self._render_nmconnection(ssid, candidate)
          updated["uuid"] = file_uuid
          updated_profiles.append(updated)
          if profile is current:
            updated_primary = updated
        self._profiles[ssid] = updated_profiles
        self._networks[ssid] = updated_primary or updated_profiles[0]
        return

      file_uuid, updated = self._render_nmconnection(ssid, existing)
      updated["uuid"] = file_uuid
      self._replace_primary_profile(ssid, current, updated)

  def _replace_primary_profile(self, ssid: str, current: dict | None, updated: dict):
    profiles = self._profiles.setdefault(ssid, [])
    if current is None:
      profiles.append(updated)
    else:
      for i, profile in enumerate(profiles):
        if profile is current:
          profiles[i] = updated
          break
      else:
        profiles.append(updated)
    self._networks[ssid] = updated

  def remove(self, ssid: str) -> bool:
    with self._lock:
      entry = self._networks.get(ssid)
      if entry is None:
        return False
      # Profiles can have duplicate keyfiles (noncanonical plus canonical, or a
      # failed-cleanup mirror). Removing only the tracked file leaves
      # the others on disk and _load would silently restore the network. Always
      # include every profile's canonical, tracked, runtime, and netplan paths
      # plus any other files matching this SSID on disk, then `rm -f` them all.
      paths: set[str] = set()
      for profile in self._profiles.get(ssid, [entry]):
        paths.add(os.path.join(self._directory, _canonical_filename(profile.get("uuid", ""), ssid)))
        tracked = profile.get("_filename")
        if tracked:
          paths.add(os.path.join(self._directory, tracked))
        runtime_filename = profile.get("_runtime_filename")
        if self._runtime_directory is not None and runtime_filename:
          paths.add(os.path.join(self._runtime_directory, runtime_filename))
        netplan_filename = profile.get("_netplan_filename")
        if self._netplan_directory is not None and netplan_filename:
          paths.add(os.path.join(self._netplan_directory, netplan_filename))
      paths.update(self._find_keyfiles_for(self._directory, ssid))
      if self._runtime_directory is not None:
        paths.update(self._find_keyfiles_for(self._runtime_directory, ssid))
      for p in paths:
        result = subprocess.run(["sudo", "rm", "-f", p], check=False)
        # `rm -f` returns 0 even if the file is absent; non-zero is a real failure
        # (FS read-only, sudo broken). Leave the in-memory entry alone. _load on
        # next start would restore the file and silently re-enable auto-connect.
        if result.returncode != 0:
          cloudlog.warning(f"NetworkStore: failed to remove {p} (rc={result.returncode})")
          return False
      del self._networks[ssid]
      self._profiles.pop(ssid, None)
      return True

  def _find_keyfiles_for(self, directory: str, ssid: str) -> list[str]:
    """Return all .nmconnection paths in a directory whose [wifi] ssid == ssid."""
    matches = []
    try:
      filenames = os.listdir(directory)
    except OSError:
      return matches
    for fname in filenames:
      if not fname.endswith(".nmconnection"):
        continue
      fpath = os.path.join(directory, fname)
      raw = sudo_read(fpath)
      if not raw:
        continue
      cp = configparser.ConfigParser(interpolation=None)
      try:
        cp.read_string(raw)
      except configparser.Error:
        continue
      if _decode_keyfile_ssid(cp.get("wifi", "ssid", fallback="")) == ssid:
        matches.append(fpath)
    return matches

  def set_metered(self, ssid: str, metered: int):
    with self._lock:
      profiles = self._profiles.get(ssid)
      if not profiles:
        return
      primary = self._networks.get(ssid)
      updated_profiles = []
      updated_primary = None
      for current in profiles:
        updated = dict(current)
        updated["metered"] = metered
        file_uuid, updated = self._render_nmconnection(ssid, updated)
        updated["uuid"] = file_uuid
        updated_profiles.append(updated)
        if current is primary:
          updated_primary = updated
      self._profiles[ssid] = updated_profiles
      self._networks[ssid] = updated_primary or updated_profiles[0]

  def get_metered(self, ssid: str) -> MeteredType:
    with self._lock:
      entry = self._networks.get(ssid)
      if entry:
        m = entry.get("metered", 0)
        if m == MeteredType.YES:
          return MeteredType.YES
        elif m == MeteredType.NO:
          return MeteredType.NO
    return MeteredType.UNKNOWN

  def contains(self, ssid: str) -> bool:
    with self._lock:
      return ssid in self._networks

  def saved_ssids(self) -> set[str]:
    with self._lock:
      return set(self._networks.keys())
